export const FETCH_BOOKS_IN_PROGRESS = "FETCH_BOOKS_IN_PROGRESS";
export const FETCH_BOOKS_SUCCESS = "FETCH_BOOKS_SUCCESS";
export const FETCH_BOOKS_FAILED = "FETCH_BOOKS_FAILED";
export const SELECT_BOOK = "SELECT_BOOK";
